input {
  file {
    path => "/var/log/bulky/*.ndjson"
    start_position => "beginning"
    codec => json
  }
}

filter {
  if [EventType] {
    mutate {
      add_tag => ["business_event"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bulky-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
